services:
  frontend:
    build: ./ClientOrderWeb
    ports:
      - "5173:5173"
    volumes:
      - ./ClientOrderWeb:/app
    environment:
      - HOST=0.0.0.0
    command: npm run dev -- --host
    depends_on:
      - backend
  
  backend:
    build: ./ClientOrderServer
    ports:
      - "3000:3000"
    environment:
      - DATABASE=postgres://postgres:postgres@db:5432/order_db
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: